### ISSUE TITLE
Looking forward to neovim dotfiles

### ISSUE THREAD

**Issue by jczhang02** [CharlesChiuGit/dotfiles#1]
Hi, @CharlesChiuGit ,
I am looking forward to your commit of neovim dotfiles! It really beautiful! 
Thanks!

**Comment by charliie-dev** [comment]
@jczhang02 Sorry for the waiting! I just gone though a full rewirte based on `ayamir/nvimdots`. It's in the final stage of polishing it.
Also my nvim dotfiles will be in [here](https://github.com/CharlesChiuGit/nvimdots), not this repo.

**Comment by charliie-dev** [comment]
Hey @jczhang02 !
I just pushed my latest version of nvimdots! Please check.
It in https://github.com/CharlesChiuGit/nvimdots.
Please let me know if there's anything wrong.
